# Generated by Django 4.0.4 on 2022-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
