# Generated by Django 4.0.4 on 2022-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_appointment_paid_patientcharges_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
