# Generated by Django 4.0.4 on 2022-06-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_patientcard_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='expiredate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
