# Generated by Django 4.0.4 on 2022-06-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_patientcard_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='approved',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
