# Generated by Django 4.0.4 on 2022-06-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_patientcard_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
